### ISSUE TITLE
support ExecutionContext

### ISSUE THREAD

**Issue by ivantopo** [kamon-io/kamon-executors#2]
Would it be possible to unwrap the executor service from a `ExecutionContext` instance and monitor it?

**Comment by dpsoft** [comment]
As pointed by @Troxid, maybe with something like this [gist][0] is enough to get an `ExecutorService` from a `ExecutionContext`?

```scala
object ExecutionContextExecutorServiceBridge {
  def apply(ec: ExecutionContext): ExecutorService = ec match {
    case null => throw null
    case eces: ExecutionContextExecutorService => eces
    case other => new AbstractExecutorService with ExecutionContextExecutorService {
      override def prepare(): ExecutionContext = other
      override def isShutdown = false
      override def isTerminated = false
      override def shutdown() = ()
      override def shutdownNow() = Collections.emptyList[Runnable]
      override def execute(runnable: Runnable): Unit = other execute runnable
      override def reportFailure(t: Throwable): Unit = other reportFailure t
      override def awaitTermination(length: Long,unit: TimeUnit): Boolean = false
    }
  }
}
```

[0]:https://gist.github.com/viktorklang/5245161

**Comment by Troxid** [comment]
@dpsoft Hello. I tried it but it prints in the logs: `ERROR main - Cannot register unsupported executor service`. As I understand, in kamon you are trying make kind of casting to a class which provide a informations for monitoring (like threads, queues, tasks and e.t.c)? `scala.concurrent.ExecutionContext.global` very well hides its implementation.

**Comment by ivantopo** [comment]
Additional info from gitter: https://gitter.im/kamon-io/Kamon?at=5a940db36fba1a703aa18f79

**Comment by yarosman** [comment]
Do you have another idea how to work with execution context? I tried these variants, but they did not work for me ((

**Comment by ivantopo** [comment]
Closing this one since it was already implemented.
